version: '3'

services:
  queue:
    image: webcenter/activemq:5.14.3
    environment:
      - ACTIVEMQ_CONFIG_MINMEMORY=512
      - ACTIVEMQ_CONFIG_MAXMEMORY=2048
      - ACTIVEMQ_ADMIN_LOGIN=roymustang
      - ACTIVEMQ_ADMIN_PASSWORD=carmesinalch
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613
