camel:
  springboot:
    main-run-controller: true

spring:
  activemq:
    broker-url: tcp://192.168.1.210:9876
    user: roymustang
    password: carmesinalch


com:
  gotcamel:
    routes:
      inbound:
        playfile: file:data/?include=.*\.txt
      outbound:
        playfile: file:output/?fileName=mydata-${dollar_sign:$}{date:now:yyyy-MM-dd-mm-ss}.txt&fileExist=Append
    ids:
      playfile: play-file
