camel:
  springboot:
    main-run-controller: true

spring:
  activemq:
    broker-url: tcp://192.168.1.210:9876
    user: roymustang
    password: carmesinalch


com:
  gotcamel:
    routes:
      playfile: file:data/?include=.*\.txt
    ids:
      playfile: play-file