camel:
  springboot:
    main-run-controller: true

spring:
  activemq:
    broker-url: tcp://192.168.1.210:9876
    user: roymustang
    password: carmesinalch

com:
  gotcamel:
    routes:
      inbound:
        movie: direct:movies
        movieCast: direct:movieCast
        person: direct:person
      outbound:
        movie: ''
        movieCast: ''
        person: ''
    ids:
      movie: movies
      movieCast: movieCast
      person: person
    names:
      movie: Movie Route
      movieCast: Movie Cast Route
      person: Person Route
