camel:
  springboot:
    main-run-controller: true

spring:
  activemq:
    broker-url: tcp://localhost:61616

com:
  gotcamel:
    baseUrlTMDB: https://api.themoviedb.org/3/
    baseUrlLFM: http://ws.audioscrobbler.com/2.0/
    routes:
      inbound:
        movie: activemq:queue:movie.requests?exchangePattern=InOut
        person: activemq:queue:person.requests?exchangePattern=InOut
        artist: activemq:queue:artist.requests?exchangePattern=InOut
        experimental: activemq:queue:experimental.requests?exchangePattern=InOut
        experimentalPattern: seda:experimental?exchangePattern=InOut
      outbound:
        movie: ''
        person: ''
        artist: ''
        experimental: seda:experimental?exchangePattern=InOut
    ids:
      movie: movies
      person: person
      experimental: experiment
      experimentalPattern: pattern-exp
    services:
      movieUrl: movie/:id
      movieUrlName: search/movie
      movieCrewCast: movie/:id/credits
      movieKeywords: movie/:id/keywords
      personUrl: person/:id
      personUrlName: search/person
    names:
      movie: Movie Route
      movieCast: Movie Cast Route
      person: Person Route
      experimental: Experimental Route
      experimentalPattern: Experimental Pattern Route

management:
  security:
    enabled: false

metric:
  headers:
#    - headerName: GoT-TYPEVALUE
#    - headerName: JMSMessageID
#    - headerName: JMSTimestamp
#    - headerName: breadcrumbId

    - headerName: Content-Type
    - headerName: GoT-TYPENAME
    - headerName: JMSDestination
    - headerName: ROUTEID


