camel:
  springboot:
    main-run-controller: true

spring:
  activemq:
    broker-url: tcp://192.168.99.100:61616

com:
  gotcamel:
    baseUrl: https://api.themoviedb.org/3/
    routes:
      inbound:
        movie: activemq:queue:movie.requests?exchangePattern=InOut
        person: activemq:queue:person.requests?exchangePattern=InOut
      outbound:
        movie: ''
        person: ''
    ids:
      movie: movies
      person: person
    services:
      movieUrl: movie/:id
      movieUrlName: search/movie
      movieCrewCast: movie/:id/credits
      movieKeywords: movie/:id/keywords
      personUrl: person/:id
      personUrlName: search/person
    names:
      movie: Movie Route
      movieCast: Movie Cast Route
      person: Person Route
