camel:
  springboot:
    main-run-controller: true

spring:
  activemq:
    broker-url: tcp://192.168.1.210:9876

com:
  gotcamel:
    baseUrl: https://api.themoviedb.org/3/
    routes:
      inbound:
        movie: direct:movies
        movieCast: direct:movieCast
        person: direct:person
      outbound:
        movie: ''
        movieCast: ''
        person: ''
    ids:
      movie: movies
      movieCast: movieCast
      person: person
    services:
      movieUrl: movie/:id
      movieUrlName: search/movie
      movieCrewCast: movie/:id/credits
      movieKeywords: movie/:id/keywords
      personUrl: person/:id
      personUrlName: search/person
    names:
      movie: Movie Route
      movieCast: Movie Cast Route
      person: Person Route
