{
 "title": "Company API",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Median Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_ms_bucket[1m])) by (le, service, route, method))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(http_request_duration_ms_sum[1m]) / rate(http_request_duration_ms_count[1m])) by (service, route, method, code)",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "95th Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_ms_bucket[1m])) by (le, service, route, method))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "count(http_request_duration_ms_count{method=\"GET\",route=\"/api/company\"}) by (method,route,status)"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "count(http_request_duration_ms_count{method=\"POST\",route=\"/api/company\"}) by (method,route,status)"
    }
   ]
  },
  {
   "title": "Requests Per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_ms_count[1m])) by (route, method)  * 60",
     "legendFormat": "{{ method }} @ {{ route }}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "count(http_request_duration_ms_count{method=\"GET\",route=\"/api/company\"}) by (method,route,status)"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_request_duration_ms_count{status=~\"^2..$\"}[1m])) / sum(increase(http_request_duration_ms_count[1m]))) * 100"
    }
   ]
  },
  {
   "title": "Appdex Score",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(\n  sum(rate(http_request_duration_ms_bucket{le=\"100\"}[1m])) by (service)\n+\n  sum(rate(http_request_duration_ms_bucket{le=\"300\"}[1m])) by (service)\n) / 2 / sum(rate(http_request_duration_ms_count[1m])) by (service)"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(http_request_duration_ms_count) by (method,route,status)",
     "legendFormat": "{{ status }} @ {{ method }} {{ route }} "
    }
   ]
  }
 ]
}