global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'docker-host-alpha'

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'GotCamel'
    scrape_interval: 10s
    metrics_path: /prometheus
    static_configs:
      - targets: ['192.168.99.1:8080']